spring:
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cache-control:
          max-age: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://172.30.1.157:3306/mosti
    username: embdev
    password: emb!1234
    hikari:
      pool-name: SpringBootJdbcHikariCP
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 120000
      maximum-pool-size: 2
      minimum-idle: 1
      max-lifetime: 580000

  output:
    ansi:
      enabled: DETECT
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: mosti-dev-admin-client
            authorization-grant-type: authorization_code
            #redirect-uri: http://localhost:8190/login/oauth2/code/keycloak
            client-secret: B2cyseDu0fPnkz0SGgi0iyqSNaMhA49d
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8443/realms/mosti-dev
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/mosti-dev

keycloak-initializer:
  initializeOnStartup: false
  masterRealm: master
  applicationRealm: mosti-dev
  client-id: admin-cli
  username: mostidevadmin
  password: 1
  url: http://172.30.1.157:8443/auth/

keycloak-admin-base-url: http://172.30.1.157:8443
keycloak-admin-id: mostidevadmin
keycloak-admin-password: 1


base-url: http://localhost:8390
expiration: 5 #분단위
# ===============================
# = Logging
# ===============================
logging:
  config: classpath:logback-dev.xml
  level:
    root: debug

log:
  config:
    path: logs
    filename: rems4eg

# ===============================
# = blockchain gateway
# ===============================
gateway:
  base-url: http://localhost:3000/api/v1 #http://172.30.1.174:8545
  # contract-id: 1260071472616860260
  # access-key: yRH4yLpXmavhanihAzg5JiraxuhwYN6WCfLDUJ4EvuUJg63emiMypCQP8KmfCP7f
  # secret-key: XE6tAhQqXt5kQWFVcigRBPjaqmw2pjyVfhcbeGhFGhCHM2MysU7YV92jCXGkqw3484XiS8VFc3qssszWSsvfGh6JR28MfJHZH9cDqHLKU5xXztgfMiB2DzekKjZ78RYr
  # environment-id: 1666842943529636665

# ===============================
# = ramda
# ===============================
# ramda:
#   base-url: https://api.luniverse.io
#   contract-id: 1260071472616860260
#   access-key: yRH4yLpXmavhanihAzg5JiraxuhwYN6WCfLDUJ4EvuUJg63emiMypCQP8KmfCP7f
#   secret-key: XE6tAhQqXt5kQWFVcigRBPjaqmw2pjyVfhcbeGhFGhCHM2MysU7YV92jCXGkqw3484XiS8VFc3qssszWSsvfGh6JR28MfJHZH9cDqHLKU5xXztgfMiB2DzekKjZ78RYr
#   environment-id: 1666842943529636665

app:
  authorized-redirect-url: http://localhost:5173/auth
